version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CS251_project
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3305:3306"

  backend:
    build: ./backend
    container_name: backend-api
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: CS251_project
      TOKEN_JWT: devsecret
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: node server.js

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install chart.js && npm run serve"
    depends_on:
      - backend
