version: "3.8"

services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=cs251database"
      - "MYSQL_PASSWORD=databaseistofun"
      - "MYSQL_ROOT_PASSWORD=databaseiscrazyfun"
      - "MYSQL_USER=csdatabase"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/attendance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: root 
volumes:
  - db_data:
